# permissions for end users to view sqlmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqlmap-viewer-role
rules:
- apiGroups:
  - scan.kappsec.io
  resources:
  - sqlmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scan.kappsec.io
  resources:
  - sqlmaps/status
  verbs:
  - get
