# permissions for end users to view zaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zap-viewer-role
rules:
- apiGroups:
  - scan.kappsec.io
  resources:
  - zaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scan.kappsec.io
  resources:
  - zaps/status
  verbs:
  - get
