# permissions for end users to edit zapopenapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zapopenapi-editor-role
rules:
- apiGroups:
  - scan.kappsec.io
  resources:
  - zapopenapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scan.kappsec.io
  resources:
  - zapopenapis/status
  verbs:
  - get
