# permissions for end users to view zapopenapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zapopenapi-viewer-role
rules:
- apiGroups:
  - scan.kappsec.io
  resources:
  - zapopenapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scan.kappsec.io
  resources:
  - zapopenapis/status
  verbs:
  - get
