name: Lint and Test Charts
on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/chart-lint.yml'



jobs:

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
